### ISSUE TITLE
feat: ability to load any url as OpenAPI schema to test against

### ISSUE THREAD

**Issue by schuur** [wbcsd/pact-api-testbed#3]
For development and for testing changes to the PACT OpenAPI schema's, it's useful to be able to provide the API test tool with a custom OpenAPI schema. Adding a `url` property to the settings will enable this. 

For convenience, a user can provide either the `version` setting, which downloads the corresponding official PACT schema from GitHub *or* the user can point to a custom URL (`url`, both http(s) and file resources are supported).

**Comment by mill6-plat6aux** [comment]
Could you elaborate a bit on the use case for using a custom OpenAPI specification?

Are you saying you want to use it to validate a new version of a Tech Spec? If so, it seems like a good idea to upload it to the pact-openapi repository (e.g. pact-openapi-2.3.0-20241010.yaml).

If users could specify their own OpenAPI specifications, it seems like they might be able to intentionally relax the restrictions and pass the test.

**Comment by schuur** [comment]
It's primarily for development purposes, but I can also imagine other scenario's where it would be good to have a local copy of the schema, for example in an environment without public internet access. 
If a user really wants to play foul to pass the test, there are easier ways to do it, and there is no way for us to enforce this anyway.

**Comment by mill6-plat6aux** [comment]
By "development purposes," do you mean the development of Tech Specs using PACT? This tool should primarily be for application vendors to perform conformance testing, so I think it should be easy for users (application vendors) to understand. It may be better to prepare a different tool for PACT development purposes.

Regarding the case where there is no Internet access, if so, you should at least specify the procedure for such users to obtain the OpenAPI specification and how to set it up to enable testing.

I think the configuration method should be as simple as possible for users (application vendors). It seems to me that the `url` MUST be set in the `README.md` description you provided in the pull request (shouldn't it be written as OPTIONAL at the bottom?).

Also, You have made a significant amount of modifications to my code, but these modifications do not seem to respect the original idea of ​​modules. For example, I implemented `github.js` as a general-purpose module that uses the GitHub API, but the newly added function does not use it. The code simply retrieves files from a specified URL. (It is an implementation unrelated to GitHub, so it feels strange to have it in this module.)

As for the act of "intentionally relaxing restrictions with a custom OpenAPI specification", rather than saying that it will lead to "playing foul", I'm concerned that if an application vendor passes Testbed and that OpenAPI specification is unique, it will provide no guarantee (it will be meaningless for other application vendors).

**Comment by schuur** [comment]
Hi Takuro san,

I think the tool can be used for:
- conformance testing by software solution providers 
- conformance testing for in-house solutions built by vendors or suppliers
- testing as part of a build pipeline for both parties
- for development of the tech spec both by PACT and other contributors
- for development of data model extensions by other parties.

In most of these cases there are scenario's (no online access, newly developed schema/code) where the flexibility of providing a URL would make sense.

I totally agree that the default/easy flow would be by just letting the user specify the official PACT schema version and test against that version.

Even better, for "official" conformance testing, it might make sense to host the tool online, and then, of course, limit the party who wishes to get a PACT conformant stamp of approval to only choose one of the published PACT schema's. 
That way also PACT will have visibility to the test output, and a conformance certifcate can be issued.

The description of the `url` setting is already in the README, but it would indeed be good to emphasise the optional and development part of it.  
As for the modular files: completely agree: the loadResource and loadTextResoucrce functions should be in a resource.js module.

edit: see https://github.com/wbcsd/pact-api-testbed/pull/4#commits-pushed-885a775

**Comment by mill6-plat6aux** [comment]
Thank you for the revised commit.
Your pull request has been accepted.

By the way, you mentioned putting this tool online. If you have plans for implementing it for conformance testing, you could share them with me so I can help you out.
If you already have a release plan, you could use GitHub Projects to set up milestones.
